server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RAG
    name: rag
    username: postgres
    password: postgres1
  profiles:
    active: openai

logging:
  file:
    name: rag.log
  level:
    net.malevy: DEBUG
    org.springframework: WARN
    com.zaxxer: WARN
  pattern:
    console: # disable logging to console

rag:
  chat:
    topk: 7
    expansionCount: 3
    similarityThreshold: 0.4
  generator:
    batchSize: 20

---
spring:
  profiles: openai

api:
  host: https://api.openai.com
  headers:
    Authorization: "Bearer ${OPENAI_API_KEY}" # API key from env.
  embeddings:
    path: /v1/embeddings
    model: text-embedding-3-small
  chat:
    path: /v1/chat/completions
    model: gpt-3.5-turbo

---
spring:
  profiles: local-model

api:
  host: http://localhost:11434
  embeddings:
    path: /api/embeddings
    model: nomic-embed-text
  chat:
    path: /api/chat
    model: gemma:7b
---
